name: Publish qadence-measurement

on:
  release:
    types:
      [published]

concurrency:
  group: fast-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish_pypi_measurement:
    if: startsWith(github.ref_name, 'measurement-')
    name: Publish qadence-measurement package to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    defaults:
      run:
        working-directory: qadence-measurement
    steps:
    - name: Check out Gradient
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build and publish package
      run: |
        hatch build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: qadence-measurement/dist
    - name: Confirm deployment
      timeout-minutes: 5
      run: |
        VERSION=$(echo "${GITHUB_REF}" | sed -E 's#refs/tags/.+-v##')
        until pip download qadence-measurement==$VERSION
        do
            echo "Failed to download from PyPI, will wait for upload and retry."
            sleep 1
        done
