name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: docs-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  # docs_hub:
  #   name: docs (qadence-hub)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./qadence-hub/actions/build_docs

  docs_commons:
    name: docs (qadence-commons)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build documentation composite action
        uses: ./qadence-commons/actions/build_docs
