name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      hub: ${{ steps.filter.outputs.hub }}
      commons: ${{ steps.filter.outputs.commons }}
      mitigation: ${{ steps.filter.outputs.mitigation }}
      measurement: ${{ steps.filter.outputs.measurement }}
      model: ${{ steps.filter.outputs.model }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            hub:
              - 'docs/**'
              - 'mkdocs.yml'
            commons:
              - 'qadence-commons/**'
            mitigation:
              - 'qadence-mitigation/**'
            measurement:
              - 'qadence-measurement/**'
            model:
              - 'qadence-model/**'

  docs_hub:
    name: docs (qadence-hub)
    needs: changes
    if: needs.changes.outputs.hub == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/build_docs

  docs_commons:
    name: docs (qadence-commons)
    needs: changes
    if: needs.changes.outputs.commons == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./qadence-commons/actions/build_docs

  docs_mitigation:
    name: docs (qadence-mitigation)
    needs: changes
    if: needs.changes.outputs.mitigation == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./qadence-mitigation/actions/build_docs

  docs_measurement:
    name: docs (qadence-measurement)
    needs: changes
    if: needs.changes.outputs.measurement == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./qadence-measurement/actions/build_docs

  docs_model:
    name: docs (qadence-model)
    needs: changes
    if: needs.changes.outputs.model == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./qadence-model/actions/build_docs