name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  docs_hub:
    name: docs (qadence-hub)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/build_docs

  docs_commons:
    name: docs (qadence-commons)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build documentation composite action
        uses: ./qadence-commons/actions/build_docs

  docs_mitigation:
    name: docs (qadence-mitigation)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build documentation composite action
        uses: ./qadence-mitigation/actions/build_docs

  docs_measurement:
    name: docs (qadence-measurement)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build documentation composite action
        uses: ./qadence-measurement/actions/build_docs

  docs_model:
    name: docs (qadence-model)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build documentation composite action
        uses: ./qadence-model/actions/build_docs
