name: Tests

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: fast-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  deploy_docs_commons:
    name: Deploy Qadence Commons docs (ubuntu)
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Qadence Commons
        uses: actions/checkout@v4
      - name: Run test composite action
        uses: ./qadence-commons/actions/test

  deploy_docs_mitigation:
    name: Deploy Qadence Mitigation docs (ubuntu)
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Qadence Mitigation
        uses: actions/checkout@v4
      - name: Run test composite action
        uses: ./qadence-mitigation/actions/test
      