name: Deploy documentation

on:
  release:
    types:
      [published]

concurrency:
  group: deploy-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  deploy_docs_commons:
    name: Deploy Qadence Commons docs (ubuntu)
    if: startsWith(github.ref, 'refs/tags/commons-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Qadence Commons
        uses: actions/checkout@v4
      - name: Run test composite action
        uses: ./qadence-commons/actions/tests

  # deploy_docs_mitigation:
  #   name: Deploy Qadence Mitigation docs (ubuntu)
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Qadence Mitigation
  #       uses: actions/checkout@v4
  #     - name: Run test composite action
  #       uses: ./qadence-mitigation/actions/test
