name: Publish

on:
  release:
    types:
      [published]

concurrency:
  group: publish-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish_pypi_commons:
    # if: startsWith(github.ref, 'refs/tags/v')
    if: startsWith(github.ref, 'refs/tags/commons-v')
    name: Publish qadence-commons package to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qadence-commons
    # timeout-minutes: 5
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Check out Gradient
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build and publish package
      run: |
        hatch build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: qadence-commons/dist
    - name: Confirm deployment
      timeout-minutes: 5
      # VERSION=$(echo "${GITHUB_REF}" | sed -E 's#refs/tags/.+-v##')
      run: |
        VERSION=$(echo "${GITHUB_REF}" | sed -E 's#refs/tags/commons-v##')
        until pip download qadence-commons==$VERSION
        do
            echo "Failed to download from PyPI, will wait for upload and retry."
            sleep 1
        done
