name: Publish

on:
  release:
    types:
      [published]

concurrency:
  group: publish-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish_pypi_commons:
    if: startsWith(github.ref, 'refs/tags/commons-v')
    name: Publish qadence-commons package to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qadence-commons
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Check out Commons
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build and publish package
      run: |
        hatch build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: qadence-commons/dist
    - name: Confirm deployment
      timeout-minutes: 5
      run: |
        VERSION=$(echo "${GITHUB_REF}" | sed -E 's#refs/tags/commons-v##')
        until pip download qadence-commons==$VERSION
        do
            echo "Failed to download from PyPI, will wait for upload and retry."
            sleep 1
        done

  publish_pypi_mitigation:
    if: startsWith(github.ref, 'refs/tags/mitigation-v')
    name: Publish qadence-mitigation package to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qadence-mitigation
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Check out Mitigation
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build and publish package
      run: |
        hatch build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: qadence-mitigation/dist
    - name: Confirm deployment
      timeout-minutes: 5
      run: |
        VERSION=$(echo "${GITHUB_REF}" | sed -E 's#refs/tags/mitigation-v##')
        until pip download qadence-mitigation==$VERSION
        do
            echo "Failed to download from PyPI, will wait for upload and retry."
            sleep 1
        done

  publish_pypi_measurement:
    if: startsWith(github.ref, 'refs/tags/measurement-v')
    name: Publish qadence-measurement package to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qadence-measurement
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Check out Measurement
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build and publish package
      run: |
        hatch build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: qadence-measurement/dist
    - name: Confirm deployment
      timeout-minutes: 5
      run: |
        VERSION=$(echo "${GITHUB_REF}" | sed -E 's#refs/tags/measurement-v##')
        until pip download qadence-measurement==$VERSION
        do
            echo "Failed to download from PyPI, will wait for upload and retry."
            sleep 1
        done

  publish_pypi_model:
    if: startsWith(github.ref, 'refs/tags/model-v')
    name: Publish qadence-model package to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qadence-model
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Check out Model
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build and publish package
      run: |
        hatch build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: qadence-model/dist
    - name: Confirm deployment
      timeout-minutes: 5
      run: |
        VERSION=$(echo "${GITHUB_REF}" | sed -E 's#refs/tags/model-v##')
        until pip download qadence-model==$VERSION
        do
            echo "Failed to download from PyPI, will wait for upload and retry."
            sleep 1
        done
