name: Temp_root

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:

  temp_init:
    uses: ./qadence-commons/.github/workflows/temp_commons.yml
