name: Temp_root

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:

  temp_init:
    runs-on: ubuntu-latest
    steps:
      - uses: ./qadence-commons/.github/workflows/
    # uses: ./qadence-commons/.github/workflows/temp_commons.yml@main
