name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      commons: ${{ steps.filter.outputs.commons }}
      mitigation: ${{ steps.filter.outputs.mitigation }}
      measurement: ${{ steps.filter.outputs.measurement }}
      model: ${{ steps.filter.outputs.model }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            commons:
              - 'qadence-commons/**'
            mitigation:
              - 'qadence-mitigation/**'
            measurement:
              - 'qadence-measurement/**'
            model:
              - 'qadence-model/**'

  test_commons_ubuntu:
    if: needs.changes.outputs.commons == 'true' || github.event_name == 'push'
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./qadence-commons/actions/tests
        with:
          python-version: ${{ matrix.python-version }}

  test_mitigation_ubuntu:
    if: needs.changes.outputs.mitigation == 'true' || github.event_name == 'push'
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./qadence-mitigation/actions/tests
        with:
          python-version: ${{ matrix.python-version }}

  test_measurement_ubuntu:
    if: needs.changes.outputs.measurement == 'true' || github.event_name == 'push'
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./qadence-measurement/actions/tests
        with:
          python-version: ${{ matrix.python-version }}

  test_model_ubuntu:
    if: needs.changes.outputs.model == 'true' || github.event_name == 'push'
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./qadence-model/actions/tests
        with:
          python-version: ${{ matrix.python-version }}