name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  test_commons_ubuntu:
    name: Qadence Commons (ubuntu)
    # if: github.event_name == 'workflow_dispatch' || contains(join(github.event.commits.*.modified), 'qadence-commons/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run test composite action
        uses: ./qadence-commons/actions/tests
        with:
          python-version: ${{ matrix.python-version }}

  test_mitigation_ubuntu:
    name: Qadence Mitigation (ubuntu)
    # if: github.event_name == 'workflow_dispatch' || contains(join(github.event.commits.*.modified), 'qadence-mitigation/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run test composite action
        uses: ./qadence-mitigation/actions/tests
        with:
          python-version: ${{ matrix.python-version }}

  test_measurement_ubuntu:
    name: Qadence Measurement (ubuntu)
    # if: github.event_name == 'workflow_dispatch' || contains(join(github.event.commits.*.modified), 'qadence-measurement/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run test composite action
        uses: ./qadence-measurement/actions/tests
        with:
          python-version: ${{ matrix.python-version }}

  test_model_ubuntu:
    name: Qadence Model (ubuntu)
    # if: github.event_name == 'workflow_dispatch' || contains(join(github.event.commits.*.modified), 'qadence-model/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run test composite action
        uses: ./qadence-model/actions/tests
        with:
          python-version: ${{ matrix.python-version }}
